# Generated by Django 4.2.16 on 2024-10-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('content', models.TextField()),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
                ('job_experience', models.TextField()),
            ],
        ),
    ]
